- src/AAA.php
- src/Config.php
- src/User.php
- Fix php warning for health checks.
> Set of fixes related to manual testing 

- composer.json
- composer.lock
- src/Config.php
- src/EmailRequest.php
- src/EmailResponse.php
- src/OrgAdmin.php
- src/PDF.php
- src/Report.php
Also using environment-specific config files.
> Fpdf related fixes

- phpunit.xml
- src/AAA.php
- src/Cache.php
- src/EmailRequest.php
- src/Session.php
- src/SmsRequest.php
- src/User.php
- tests/unit/CacheTest.php
- tests/unit/SessionTest.php
- tests/unit/UserTest.php
- Cache class redesign and tests
- Some generic tests for Session
- Set up code coverage for PHPUnit
> More automated tests

- src/AAA.php
- src/EmailRequest.php
- src/SmsRequest.php
- src/User.php
- tests/unit/UserTest.php
- Tests for username and password regexes, with the default lengths (if pw set to be random)
> Ensure the length of the username is enforced. 

- src/EmailRequest.php
- src/EmailResponse.php
- src/OrgAdmin.php
Optionally send admin emails to an email manager address with original recipient in the subject.
> Support for HO email manager

- src/EmailRequest.php
- src/Identifier.php
- src/SmsResponse.php
- tests/TestConstants.php
- tests/unit/EmailRequestTest.php
- tests/unit/fixtures/email-newsite-extraip.txt
- tests/unit/fixtures/email-newsite-multipart.txt
- tests/unit/fixtures/email-sponsor-autoconcat.txt
- tests/unit/fixtures/email-sponsor-empty.txt
- tests/unit/fixtures/email-sponsor-shortnumber.txt
- tests/unit/fixtures/email-sponsor-shortnumber2.txt
- tests/unit/fixtures/email-sponsor-signature.txt
- New site email picks up extra IP from metadata
- Sponsor email: signature parsed, finds extra (too short) numbers
- Correctly parse multi-level multipart messages.
> Fix email parsing issues

- src/GovWifiException.php
- src/PerformancePlatformClient.php
- src/PerformancePlatformReport.php
- src/ReportCompletionRate.php
- src/ReportVolumetrics.php
- tests/unit/PerformancePlatformClientTest.php
- tests/unit/PerformancePlatformReportTest.php
- tests/unit/ReportVolumetricsTest.php
- Volumetrics reports added. 
- Manual update.
> Performance platform integration.

- src/EmailRequest.php
- src/sns/index.php
- Extract and save sender name to EmailRequest.
- Prioritise using returnPath for from address
> Add the display name of the sponsor to the email address when available.

- src/sns/index.php
Fix validation to pick up malformed return path and use the from field instead.
> Fix to cater for malformed return path in PINS emails.

- src/EmailRequest.php
Fixed my change to strpos.
Logged out of my other account with 2FA. Whoops.
> Update EmailRequest.php (Recreated, closed SysVoid PR)

- src/Config.php
- src/EmailRequest.php
- src/EmailResponse.php
- src/GovWifiBase.php
- src/providers/EmailProvider.php
- src/providers/EmailProviderFactory.php
- src/providers/SnsEmailProvider.php
- src/sns/index.php
- tests/TestConstants.php
- tests/unit/EmailRequestTest.php
- tests/unit/GovWifiBaseTest.php
- tests/unit/providers/EmailProviderFactoryTest.php
So it can be tested.
- Move process request logic to class from entry point
- Pull out SNS logic to it's separate Provider to reduce 3rd party dependency.
- Add apostrophe to email regex
> Refactor EmailRequest

- templates/email/html/wifi-details-20170308
- templates/email/html/wifi-details-self-signup-20170308
- templates/email/wifi-details-20170308
- templates/email/wifi-details-self-signup-20170308
- Modified copy for IPhone instructions
- Fixed clickable link in Windows 7
> Email copy changes 20170322

- src/timedjobs/performanceplatform/index.php
- src/timedjobs/survey/index.php
Sorry about it being 2 commits. Should be able to squash these in the merge tool on GH.
Fixed the code style to make it more consistent and changed `==` to `===` where the API key is compared (since the API key should always be the same type anyway).
> Fix code style

- src/clients/index.php
I believe `===` is more appropriate here.
> Change == to ===.

- src/PerformancePlatformClient.php
- src/PerformancePlatformReport.php
- src/ReportAccountUsage.php
- src/ReportActiveLocations.php
- src/ReportCompletionRate.php
- src/ReportVolumetrics.php
- src/timedjobs/performanceplatform/index.php
- Move categoryName and categoryValue to extras, make them optional
> Add support for reporting the number of active locations to PP.

- src/ReportVolumetrics.php
- src/timedjobs/performanceplatform/index.php
- Enable completion rate backfill functionality - weekly stats.
- Add more flexible logic for daily data initialisation.
- Fix sponsor condition for volumetrics data.
> Performance Platform updates / fixes

- templates/email/html/wifi-details
- templates/email/html/wifi-details-self-signup
- templates/email/wifi-details
- templates/email/wifi-details-self-signup
Remove the word "short" from the pw help to support old-style passwords should they ask for a reminder.
> Email copy updates

- templates/email/html/wifi-details
- templates/email/html/wifi-details-self-signup
- templates/email/wifi-details
- templates/email/wifi-details-self-signup
- Plus fix a few naked quotes in html
> Add reference to unique credentials to email templates

- src/AAA.php
- src/Session.php
- src/User.php
- templates/email/html/wifi-details
- templates/email/html/wifi-details-self-signup
- templates/email/wifi-details
- templates/email/wifi-details-self-signup
- tests/TestConstants.php
- tests/acceptance/config/radius-accounting-start.json
- tests/unit/AAATest.php
- tests/unit/UserTest.php
- Email template changes
- Handling of malformed session IDs
> Live release 20170725

- src/AAA.php
- tests/unit/AAATest.php
Increase the code coverage of the AAA class to 100%
To do this, some changes to the AAA class have to be made - one is a formatting change and the other is removing a default in a case statement that can never be triggered.
Its best practice to cover all statements within the code
Anyone but me
> Increase code coverage to 100%

- templates/email/html/existing-user
- templates/email/html/newpassword
- templates/email/html/wifi-details
- templates/email/html/wifi-details-self-signup
- templates/email/newpassword
- templates/email/wifi-details
- templates/email/wifi-details-self-signup
- Update T&Cs url,
- Change newpassword copy,
- Switch boldness to username / pass only, leave the labels normal.
> Update T&Cs url, change newpassword copy.

- src/AAA.php
- templates/email/html/existing-user
- templates/email/html/newpassword
- templates/email/html/wifi-details
- templates/email/html/wifi-details-self-signup
- templates/email/newpassword
- templates/email/wifi-details
- templates/email/wifi-details-self-signup
- templates/pdf/newsite
- tests/unit/AAATest.php
- Update T&Cs url, change newpassword copy
- Pull comment on configuration reload
- Increase AAA code coverage to 100%
> Live release 20180831

- composer.json
- composer.lock
- src/SmsResponse.php
- Upgrade client version, 
- remove serviceID parameter, 
- upgrade error log handling
> Upgrade Notify client

- src/DB.php
- src/timedjobs/performanceplatform/index.php
- tests/unit/DBTest.php
- In preparation for the read replica setup.
> Allow multiple db connections

- src/AAA.php
- src/DB.php
- src/Session.php
- src/timedjobs/performanceplatform/index.php
- tests/unit/AAATest.php
- tests/unit/DBTest.php
Contents:
- Change stop event with no start event to 204 #102
- Reduce risk of deadlock on accounting update #101
- Allow multiple db connections #99 
- Switch over statistics queries to read replica
> Live release 20170921

- tests/TestConstants.php
This is so that we can build the project and run the
automated tests without secrets.
> Use a fake password, which will be used by the build
