alphagov/govwifi

src/AAA.php, src/Config.php, src/sms/index.php, src/sns/index.php
- Fix PDO include,
- Fix function name
- Prepend the firetext keyword to the message (if provided) so we can handle the keyword "agree" on short numbers. "Go" is stripped later in the process, so no change is necessary there.
=> Firetext keyword handling, fixes.

src/sns/index.php
This could indicate an issue with the email setup (there is an email address that is not handled by the system) - however most likely someone just cc'd us in by mistake.
=> Extend logging for cases when we do receive an email but a command is not found.

src/sns/index.php
As shown by a test with a @greenfinch.com email address, region-internal SES emails override the return-path parameter, as such it is not reliable for domain/admin validation.
=> Allow any return-path - check email "from" only

src/EmailRequest.php, src/EmailResponse.php, src/timedjobs/survey/index.php, templates/email/html/wifi-details-20170308, templates/email/html/wifi-details-self-signup-20170308, templates/email/logrequest, templates/email/newsite, templates/email/newsite-help, templates/email/wifi-details-20170308, templates/email/wifi-details-self-signup-20170308
- Update admin email copies to latest version
- Change newsite logic: not to send PDF with help email; actually send the help email when IPs are not found in the first newsite request.
- Change android help text - emphasise scroll down and logically separate password 
- Add link to online instructions at the beginning of the email
=> Admin email journey updates 20170411

src/PerformancePlatformClient.php, src/PerformancePlatformReport.php, src/ReportAccountUsage.php, src/ReportCompletionRate.php, src/ReportUniqueUsers.php, src/sms/index.php, src/timedjobs/performanceplatform/index.php, src/timedjobs/survey/index.php
- Add extra logging for the sendSimpleMetrics call in PP report.
- Add number of transactions (number of users per site per day) to account usage stats, allow data reinitialisation.
- Rewrite unique users to calculate the averages directly and skip weekends.
=> PerformancePlatform report updates.

src/ReportUniqueUsers.php
- Rename month field, send prev month start as timestamp for unique users stat. This allows for more consistent separation of data and fixes the date range it corresponds to.
=> Performance Platform fix for active users

src/AAA.php, src/User.php, tests/unit/UserTest.php
- Calculate the md5 hash of the session ID instead of appending it directly to the username when constructing the key for the cache (memcached).
If the key is malformed - contains a space or other special character -  when saving data to memcached the process will hang indefinitely instead of returning an error (and eventually execution timeout kicks in at 30 seconds). Using the hex representation of the md5 hash this can not happen. Considering the random nature of the of the actual session IDs and the fact that the username is prepended to the final key the chance of key clash is negligible. 
- Skip starting an accounting session for invalid users.
=> Handle malformed Acct-Session-Ids

src/AAA.php, src/Session.php, src/User.php, tests/TestConstants.php, tests/acceptance/config/radius-accounting-start.json, tests/unit/AAATest.php, tests/unit/UserTest.php
- Update all sessions on start and stop, not just stop. 
- Leave AP field intact (so for HO we should have both fields filled, for Plymouth, only the building ID)
- Possible issue: if Plymouth starts sending accounting requests (they don't at the moment) AND those accounting requests are not agreeing with the Access requests in their building ID (sending the AP instead) The previously (rightly) set building ID will be deleted from the record, while AP will not get set at all.
=> Update session record with building identifier on accounting

src/AAA.php, src/User.php, tests/unit/AAATest.php
- Make sure we are sending a negative instead of an empty response on authorisation failure. 
- Take into account the new "invalid user" setting. (in preparation for user invalidation)
- More tests.
- Fix error message for when the user is not found and looked for by contact instead of login.
=> AuthoriseResponse updates

src/AAA.php, src/User.php, templates/email/existing-user, templates/email/html/existing-user, templates/email/html/newpassword, templates/email/newpassword, tests/unit/AAATest.php
- New email templates for password journey
- AuthoriseResponse updates
- Fix for suppressing warning when the identifier is not set (happens for HO test accounting requests)
=> Live release 20170817

templates/pdf/newsite
- Also modify wording slightly for confirming support email address.
- Config update required. See PR103 [here](https://github.digital.cabinet-office.gov.uk/CTS-GovWifi/govwifi-build/pull/103)
=> Pull comment on configuration reload 

src/AAA.php, src/Session.php
- Only save session on start request if we have a building identifier to save. 
- Add AP to query conditions if we have an AP to add.
- Remove AP condition as it proved inconsistent in staging tests, add exception handling and custom success message so we can gauge the extent of failed updates without hitting the generic alarm.
- Add DB transaction around update query
=> Reduce risk of deadlock on accounting update

src/AAA.php, tests/unit/AAATest.php
In freeradius, responding with a 404 results in a spurious error message
in the free radius logs which is noisy - changing this to a 204 should
stop this error message occurring. Free radius expects the response to
be a 2xx or 5xx - this error is not a server error, so 204 is the most
appropriate response
Code review, check tests pass
Anyone but me
=> Change stop event with no start event to 204

src/EmailRequest.php, tests/TestConstants.php, tests/unit/EmailRequestTest.php, tests/unit/fixtures/email-sponsor-base64-htmlonly.txt, tests/unit/fixtures/email-sponsor-base64.txt
Add base64 decode for email body parsing where the appropriate Content-Transfer-Encoding is set. Make sure that the encoded string does not get mangled by turning the body to lowercase at the start.
=> Handle BEIS sponsor email problem when sent from outlook

src/AAA.php
We've had a few alarms firing today caused by a significant traffic spike opening up several hundred database connections per minute as opposed to the 4-5 average.
This caused accounting updates to throttle. 
This change will remove the unnecessary early initialisation of the Site class for every incoming request.
=> Remove early site initialisation in order to reduce the number of queries against the database.

src/AAA.php, src/DB.php, src/OrgAdmin.php, src/User.php, tests/unit/AAATest.php
Make DB connection lazy.
Most of our authorisation requests are served from cache - in these cases explicit database connection is not required. This change makes sure that a database connection is only created when one is requested, as opposed to at instanitation of the DB class.
Remove superfluous creation of a Site instance. Also make sure that a database connection is only requested when it is actually used.
Make sure the username is in the right format before trying to look it up in the DB. Restrict valid username regex further, improve log message for empty user details.
=> Performance optimisations

tests/acceptance/RadiusServerTest.php, tests/acceptance/config/run-eapol-test.sh
eapol_test requires an IPv4 address passed into it, but we only have the container name.
Previously we were performing the address lookup by inspecting the /etc/hosts file. This falls over when using docker-compose to manage the containers as it uses a DNS server.
PHPs gethostbyname will look at both /etc/hosts and DNS
=> Use gethostbyname to get IP address instead of grepping /etc/hosts

src/AAA.php, tests/unit/AAATest.php
When a user logs into the service we record their last login time and then use that as part of the data clearing procedure.  Any account which hasn't logged into GovWifi for 12 months is then purged.
=> Set the last_login field for a user on an accepted postauth request

tests/acceptance/RadiusServerTest.php
We are removing logging from the critical path, and need this test to
ensure that we don't authenticate people accidentally by forcing the
rest module in radius to be redundant.
=> Test that auth reject works

tests/acceptance/RadiusServerTest.php
I'm working on removing the old PHP/apache healthcheck and using new Ruby implementation instead. 
Steps:
- remove this test (I'm here now) to make `govwifi-frontend` repo build on Jenkins pass, as Jenkins points to master branch of tests from `govwifi` repo
- push out `govwifi-frontend`
- implement the new test in `govwifi`
=> Remove old Radius healthcheck
